### ISSUE TITLE
Checklist for next dashboard deployment

### ISSUE THREAD

**Issue by samanthacsik** [UCSB-MEDS/shiny-dashboard#22]
- [ ] update `{tmap}` on the server
- [ ] update `{shinyjs}` on the server
- [ ] add new data files: `admissions.rds`, `apps_clean.rds`, `diversity_stats.rds`, `enrolled.rds`, `ipeds.rds`, `meds_placement_cleaned.rds`, `mesm_placement_cleaned.rds`, `status_data.rds`, `ug_geoms.rds`, `us_state_geoms.rds` (though I don't think that one has changed at all?)
- [ ] copy over `www/google-analytics.html`
